Make tidyc support pipe mode and be more robust with file updating.
Fix cmdline parsing for no args, and to support -- to stop parsing args.

Add do_tidyc() function to format stdin to stdout using pipes between
sed and indent. Add support for pipeline operation with no file
arguments. Process files more robustly using a mktemp output file
before moving files around. Add support for correctly moving the
original file to a *~ backup before overwriting it.

Update tidyc_test to use redirection for input/output, and improve
output a little.

diff --git a/tidyc b/tidyc
--- a/tidyc
+++ b/tidyc
@@ -27,8 +27,10 @@ DSC_OPT=1
 DQT_OPT=0
 DAB_OPT=1
 IEC_OPT=1
-while [ -z "${1##-*}" ]; do
+while [ "${1:0:1}" == "-" ]; do
   case "$1" in
+    # Stop parsing cmdline args at --.
+    --) shift; break ;;
     # Force particular styles, dropping suggested defaults.
     -L|-linux) INDENT_ARGS="-linux" ;;
     -K|-kr) INDENT_ARGS="-kr" ;;
@@ -206,14 +208,32 @@ else
   SED_POST2="${SED_POST2}"'s:/\*\!:/**:g;'
 fi
 
-# Preprocess code with sed.
-sed -r -i "${SED_PRE1}" "$@"
-sed -r -i "${SED_PRE2}" "$@"
+# Turn on pipe failure support.
+set -o pipefail
 
-# Tidy code using indent.
-echo Running: indent ${INDENT_ARGS} "$@"
-indent ${INDENT_ARGS} "$@"
+# Tidy code from stdin to stdout.
+do_tidyc () {
+  # Preprocess code with sed.
+  sed -r "${SED_PRE1}" |
+  sed -r "${SED_PRE2}" |
+  # Tidy code using indent.
+  indent ${INDENT_ARGS} |
+  # Postprocess code with sed.
+  sed -r "${SED_POST1}" |
+  sed -r "${SED_POST2}"
+}
 
-# Postprocess code with sed.
-sed -r -i "${SED_POST1}" "$@"
-sed -r -i "${SED_POST2}" "$@"
+# Tidy stdin or cmdline files.
+if [ "$1" == "" ]; then
+  do_tidyc
+else
+  for f in "$@"; do
+    o=$(mktemp "$f".XXXX) && 
+    {
+      do_tidyc < "$f" > "$o" &&
+      mv -f "$f" "$f~" &&
+      mv -f "$o" "$f" ||
+      rm "$o"
+    }
+  done
+fi
diff --git a/tidyc_test b/tidyc_test
--- a/tidyc_test
+++ b/tidyc_test
@@ -17,12 +17,12 @@ tests=${@:-tests/*.out}
 # Run a cmd and fail the test if cmd fails.
 run_test () {
   echo "Running: $@" >&2
-  "$@" || fail_test "returncode=$?"
+  "$@" || fail_test
 }
 
 # Fail the test and exit.
 fail_test () {
-    echo "Failed! $1" >&2
+    echo "FAIL" >&2
     exit 2
 }
 
@@ -35,9 +35,9 @@ do_test () {
   args="${name//_/ -} "; args=${args#* }
   echo
   echo $expect
-  cp $input $output
-  run_test ./tidyc $args $output
+  run_test ./tidyc $args <$input >$output
   run_test diff -q $expect $output
+  echo "PASS" 
   rm -f $output
 }
 
